\mainmatter

# Systems of human judgment

An understanding of the mental traps to which we are prone
can help us avoid them. Kahneman's book [-@kahneman_2013]
*Thinking Fast and Slow* is a good starting point for
thinking about the strengths and limitations of human
thinking processes.

Encounter with "educating gossip", as Kahneman calls it, is an
important and necessary part of learning effective judgment.
This present booklet avoids detailed discussion of methodology,
instead focusing on what is, in Kahneman's sense, "educating
gossip".  Such "gossip" can be important for improving the quality 
of judgments and decisions

Important themes are

* We easily think associatively, ... metaphorically, casually,
but statistics requires thinking about many things at once ...
* We too readily judge decisions by outcome, rather than by how they are made.
* We have "an excessive confidence in what we think we know".
* We have two selves --- an experiencing self and a remembering self
    + These do not always have the same interests.
* Automatic memory formation has its own rules
    + This is exploited to improve the memory of a bad episode

## System 1 and System 2 --- further comments

Humans have been conditioned to respond quickly to immediate
risks and challenges, without stopping to consider too carefully
whether what we heard was a false alarm. They also have the
ability, when the occasion seems to demand it, to stop to ponder.
This is the basis for Kahneman's categorization of human thought 
processes as of two types --- System 1 which jumps rapidly to 
make a judgment, and System 2 which takes time for careful 
consideration.

* System 1 responds quickly to immediate dangers, but is prey to
    priming (suggestive language), framing (response to a choice
    depends on how it is presented), affect (feeling or emotion),
    memory illusions, illusions of truth, ...
    + "... associative memory, the core of System 1, attempts to give a coherent
account of what is going on in our world in any instant"  
    + System 1 may answer an easier question in place of a harder.
* System 2 is the process involved when, before making a decision,
we think carefully through the issues involved.
    + Invoke System 2, when time allows, for decisions that matter. 

System 1 Features are

* It may substitute an easier question
* It responds to priming, framing, affect, memory illusions,
    illusions of truth, ...
* It has little understanding of logic and statistics
* It cannot be turned off
* When flummoxed, it calls on System 2

System 2 features are

* It keeps you polite when angry, alert when driving at night
* In its world, gorillas do not cross basket-ball courts ...
* There are some vital tasks that only System 2 can perform
* Problems that put 1 & 2 in conflict may require large
    mental effort & self-control to overcome the impulses and
    intuitions of System 1
    
Further comments are

* Untrained humans are poor intuitive statisticians.
     + Judgments about statistical issues may require us to think
     about more than one, even many, things at once.
     + Too often, we jump to conclusions, without careful assessment.
     + Or, we may not be equipped to make an informed and carefully
     thought through decision.
* System 1 and System 2 are both amenable to training
    + A well-trained System 2 is the key to a better System 1.  
* Healthy living is a compromise
     + Recognize situations where mistakes are likely
     + Aim to avoid significant mistakes when the stakes are high
* Kahneman describes System 1 and System 2 as "fictions"! I prefer
to describe them as providing a model that is helpful in 
accounting for the way that humans make judgments.
    + Human mental quirks make it useful to think of these as agents.
    + Stories about active agents who have personalities, habits, and 
abilities readily take root in our minds
* Ascribing calculation to System 2 is shorthand for ...
    + "This requires mental effort. Do not do when driving!"
    + Pupils will be dilated, and heart rate elevated.  

## The Intuition of Professionals

Effective professional training is designed to ensure that at least
some of the results of well-tuned System 2 expert judgment operate
at a System 1 level.

> The situation has provided a cue; this cue has given the expert access to information stored in memory, and the information provides the answer.  Intuition is nothing more and nothing less than recognition.  
[@simon1992explanation, "What is an Explanation of Behavior?"]

Simon's comments were in part based on the study of chess masters.

> ... An expert is one who has built a deep familiarity with the patterns of a given domain and, thus, has a robust body of work from which to reference when making decisions.^[
<http://www.euclidean.com/expert-intuition-and-machine-learning/>]

### Obstacles to effective judgment {-}

The biases that Kahneman documents can readily take over, where 
there should be carefully reasoned and informed System 2 judgment.

* Financial firm executive, explaining why he invested in Ford stock:  
    + "Boy, do they know how to make a car!"
    + An easier and related question (do I like Ford cars?) came
    readily to mind and determined his choice.
* Exemplifies the _affect_ heuristic --- decisions are guided
by like/dislike feelings, with little deliberation or reasoning.

Even those who are experts in their field can be similarly prone to judgments
that have no foundation in fact:

> "But you're not an MD like I am. The problem with you is that you
do not understand medicine.  You see, medical statistics are not
like other statistics."  
[Prostate biopsy specialist, in response to evidence that screening
is counterproductive. [@levitin_2015, p.247]]

The following comment appeared in a discussion of the response 
to a U.S. Preventive Services assessment that prostate screening,
when used in accordance with then current treatment practices,
was doing more harm than good.^[Association of Professional 
Psychologists, web post on @arkes2012psychological]  

> Even faced with ... evidence ... [from] a ten-year study of around  250,000 men that showed the test didn’t save lives, many activists and medical professionals are clamoring for men to continue receiving their annual PSA test.  

New evidence emerges as time proceeds, and there are advances in the 
approach to treatment.  At least part of the problem has been a rush 
to treatments that themselves risk increasing damage and the risk of 
death.  Note the comment in @brawley2018prostate that

> Over the past few years, the benefit‐to‐harm ratio has 
improved in favor of benefit if the man understands that 
active surveillance may be a reasonable path if diagnosed.

## A demand for discipline & careful thought 
    
* We make judgments based on evidence that is too limited
* We are easily fooled by irrelevancies
    + Kahneman has brought together evidence on what & how.
* Even when data are there for the taking, someone has 
to notice, to collate the data, and to understand its uses
and limitations
* Randomized controlled experiments (RCTs) are often the ideal, but 
require meticulous planning. If effects of interest are small, 
the numbers required may be very large.  See further, 
Subsection \@ref(ss:rct)
* Observational data does not easily, if at all, substitute for
the use of RCTs.  It is no easy matter to adjust for sources
of bias
* Keep in mind Yule-Simpson "paradox", which we will encounter
later in Subsection \@ref(sec:yule1)
    + The paradox lies in the failure of human intuition to
    accommodate straightforward arithmetic!
    + <https://www.youtube.com/watch?v=ZDinnCwP3dg> 
    (This animated video provides a short overview)

## Further examples

### A simple (and, arguably, trick) example {-}

Linda is a 31-year old philosophy graduate, single,
outspoken, and bright.  As a student, she was deeply
concerned with issues of discrimination and social
justice, and also participated in anti-nuclear
demonstrations.  Which of the following is more probable?  

* Linda is a bank teller.
* Linda is a bank teller, and active in the feminist
movement.

Adding the further descriptor "active in the feminist
movement" can only lower the probability, or just possibly
leave it unchanged.  Instead of assessing the balance of
probabilities, we are tempted to ask which description best
meshes with what we have been already told about Linda.

"Linda is active in the feminist movement" is the single 
descriptor" that respondents see as best fitting Linda.
While that was not what was asked, one has to pay close
attention to prevent System 1 from substituting that for
the question that was asked.  Note that the correct 
answer will be "a bank teller", irrespective of the way 
that Linda was characterized before the question was asked.

In part, the issue is one of use of language. The "correct"
answer is asking us to use the word "likely" in a strict
technical sense.

### Even careful critics sometimes get it wrong {-}
    
An irony is that Kahneman was, as he has acknowledged, 
himself fooled into taking at face values papers that 
claimed to show that verbal concepts could have the 
effect of altering behaviour.  Thus

* Being asked to write down stories about unethical deeds
made people more likely to want to buy soap;
* Subtly drawing attention to money, e.g., leave banknotes
lying around, made people feel more self-sufficient, and 
care less about others;
* Priming people with old age related words leads people to
walk more slowly away from the lab as research
assistants armed with stopwatches timed their movements.

As @ritchie2020science notes (p.28) Kahneman was not alone 
in being fooled --- the study about priming with old age 
related words has been extensively cited in
psychology textbooks. None of these claims have stood up
in attempts at replication, with larger numbers and with
greater care to avoid unconscious sources of bias. Thus,
in the replication of the study relating to age-related
words, infra-red beams were used to measure time taken
to walk between two points in a hallway, rather than
research assistants who knew the group to which
participants had been assigned.

### Think again --- a very simple example {-}

Is symptom X associated with disease A?

|| Has Disease | No Disease
| ----------------- | -- | --- | ---
| Symptom X Present | 20 | 10
| Symptom X Absent | 80 | 40

The symptom occurs with the same relative frequency, whether or
not a person has the disease.
Nisbett comments that most people, including nurses and doctors,
interpret such evidence wrongly [@nisbett, pp.129-130].

### Do you understand risk {-}

See the 2-minute test 
{"Do you understand risk?"](http://www.riskliteracy.org/)^[http://www.riskliteracy.org/]

## Misbehaving humans!

The discipline of "behavioural economics" largely took shape
as a result of the work of Richard Thaler.  Kahneman was
one of two mentors who strongly influenced Thaler --- the
other was Amos Tversky, who had worked closely with Kahneman.

@thaler2015misbehaving explores the extent to which humans do
not behave like the rational agents of classical economics, 
agents to whom Thaler gives the name "econs". Added to the
irrationality with which we often act is that our personal
priorities are unlikely to align precisely with those of econs.

Note also comments in Part 4 of @kahneman_2013, titled
"A conversation with the discipline of economics".
In a discussion on "The Prospect theory model of choice",
Kahneman comments on

* "... unfortunate tendency to treat problems in isolation"
* Framing effects --- inconsequential features shape choices

Hence, "a challenge to the assumptions of standard economics".    

## Negotiating Life in an Uncertain World^[These questions came originally from the Harding Center web site <https://www.hardingcenter.de/en>.]

Questions that it can be helpful to ask include

1. Risk of what? (Showing a symptom, ..., Death)
2. What is the time frame? (next 10 years, or lifetime)
3. How big is the risk? (Look at risk in absolute terms)
4. Does the risk apply to me? (Age, sex, health, ...)
5. What are the harms of "finding out"? (False alarms, invasive
diagnostic procedures, unnecessary or dangerous treatments.)
