\backmatter

# Books, videos, and websites {#app:more}

### Books (all been referred to in the text)

* @kahneman_2013 . Thinking, fast and slow.
    + [Interview with Kahneman](https://www.youtube.com/watch?v=PirFrDVRBo4 "Interview")^[<https://www.youtube.com/watch?v=PirFrDVRBo4>]
    + [A brief animated overview of some key points](https://www.youtube.com/watch?v=uqXVAo7dVRU&t=28s)^[<https://www.youtube.com/watch?v=uqXVAo7dVRU&t=28s>]
* @smith-sd . Standard Deviations: Flawed Assumptions, Tortured Data, and Other Ways to Lie with Statistics
    + [Brian Lehrer interview with Smith](http://www.garysmithn.com/standard-deviations.html)^[<http://www.garysmithn.com/standard-deviations.html>]
* @ellenberg_2015 . How not to be wrong.
    + [There are links to several Ellenberg video clips](http://www.thelavinagency.com/news/new-videos-jordan-ellenberg-runs-the-numbers)^[<http://www.thelavinagency.com/news/new-videos-jordan-ellenberg-runs-the-numbers>]
* @levitin_2016 . A field guide to lies and statistics.
* @nisbett . Tools for smart thinking.
* @cairo_2013 . The functional art: an introduction to information
	graphics and visualization.
* @ritchie2020science . Science fictions: Exposing fraud, bias, 
negligence and hype in science.

### Videos {-}

* [Randomized controlled trials --- animated summary of key issues](https://www.youtube.com/watch?v=Wy7qpJeozec)^[<https://www.youtube.com/watch?v=Wy7qpJeozec>]
* [Yule-Simpson paradox --- animated video](https://www.youtube.com/watch?v=ZDinnCwP3dg)^[<https://www.youtube.com/watch?v=ZDinnCwP3dg>]

### Websites {-}

* [BBC links to helpful web resources](http://www.bbc.co.uk/editorialguidelines/guidance/reporting-statistics)^[<http://www.bbc.co.uk/editorialguidelines/guidance/reporting-statistics>]
* The [Cochrane Center](https://www.cochrane.org/)^[<https://www.cochrane.org/>]
* [Harding Center for Risk Literacy](https://www.hardingcenter.de/en)^[<https://www.hardingcenter.de/en>]
* [Winton Centre for Risk and Evidence  Communication](https://wintoncentre.maths.cam.ac.uk/)^[<https://wintoncentre.maths.cam.ac.uk/>]

