
# References {-}

```{r include=FALSE}
bib = knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown', 'htmlwidgets', 'markdown',  'rmdformats'
), file = NULL)
bib = unlist(bib)
bib = gsub("'(Htmlwidgets|iframes|TeX Live|LaTeX)'", '\\1', bib)
xfun::write_utf8(bib, 'packages.bib')
# embed fonts
if (knitr::is_latex_output()) {
  pdfs = list.files(knitr::opts_chunk$get('fig.path'), '[.]pdf$', full.names = TRUE)
  invisible(lapply(pdfs, embedFonts))
}
```

<div id="refs"></div>

# About the Author {-}

<!-- # About the Author {#author .unnumbered}
Following a first in Mathematics at what was then Auckland University College, and several teaching and lecturing positions,  -->

For the major part of his career, John Maindonald worked with other 
researchers as a quantitative problem solver.
He has held positions at Victoria University of Wellington, in DSIR, in HortResearch Crown Research Institute (now Plant and Food), and at The Australian National University (ANU). He joined the then newly formed ANU Centre for Bioinformation Science in 2001, formally retiring in 2005.
<!-- Since formal retirement in 2005, he has been a visiting fellow in the ANU Mathematical Sciences Institute. -->
Between 1983 and 1996, and occasionally after 1996, he reviewed the statistical content of numerous papers that appeared in DSIR (later, Royal Society) journals, notably the New Zealand Journal of Agricultural Research and the New Zealand Journal of Crop and Horticultural Research. 

Between 2003 and 2015, he fronted 35 short courses (one week, or less) 
across different parts of Australia that demonstrated the use of the open source R data analysis and graphics system for data analysis purposes. 
<!-- These were conducted at the request of, or under the auspices of, a variety of Australian and other academic, research, and government organizations. -->
He is the author of a book on Statistical Computation, and the senior author of “Data Analysis and Graphics Using R — An Example-Based Approach” (Maindonald and Braun 2010). This has sold more than 11,000 copies over
the three editions.

